package cmd

import (
  "fmt"
  "strings"
  "os"
  "os/user"
  "github.com/codegangsta/cli"
  "../cert"
)

type LocalEnvironment struct {
  host string
  user string
}

func getLocalEnvironment () LocalEnvironment {
  // Acquire Hostname
  host, err := os.Hostname()
  if err != nil {
    fmt.Println(err)
  }

  // Acquire the current user
  user, err := user.Current()
  if err != nil {
    fmt.Println(err)
  }

  return LocalEnvironment{
    host: host,
    user: user.Username,
  }
}

func NewCertificate () cli.Command {

  local := getLocalEnvironment()

  return cli.Command{
    Name: "create",
    Aliases: []string{"c"},
    Usage: "Create a certificate.",
    Flags: []cli.Flag{
      cli.StringFlag{
        Name: "passphrase, p",
        Usage: "Optional PEM encryption key.",
      },
      cli.IntFlag{
        Name: "bits, b",
        Value: 2048,
        Usage: "Keypair bit size.",
      },
      cli.IntFlag{
        Name: "expire, e",
        Value: 3650,
        Usage: "Expiration in days (10yrs by default).",
      },
      cli.StringFlag{
        Name: "key, k",
        Usage:"Private key file. Key is autogenerated if this is left blank.",
      },
      cli.StringFlag{
        Name: "certauth, ca",
        Value: "self",
        Usage: "Signing certificate (CA). If this is not specified, the certificate will be self-signed.",
      },
      cli.StringFlag{
        Name: "output, d",
        Usage:"Output directory where the certificate and private key are stored.",
      },
      cli.StringFlag{
        Name: "org, o",
        Value: local.user + " computer",
        Usage: "Organization",
      },
      cli.StringFlag{
        Name: "orgunit, ou",
        Value: "localhost",
        Usage: "Organizational Unit",
      },
      cli.StringFlag{
        Name: "country, c",
        Value: "Earth",
        Usage: "Country",
      },
      cli.StringFlag{
        Name: "commonname, cn",
        Value: local.host,
        Usage: "Common Name",
      },
      cli.StringFlag{
        Name: "state, s",
        Value: "Unknown",
        Usage: "Province, Region, County or State",
      },
      cli.StringFlag{
        Name: "city, l",
        Value: "Unknown",
        Usage: "Town/City/Locality",
      },
    },
    Action: MakeCertificate,
  }
}

func MakeCertificate (c *cli.Context) {
  cn := c.String("commonname")
  cn = strings.Replace(cn, " ", "_", -1)

  // If no private key is specified, make one.
  // if !c.IsSet("key") {
    pk := cert.CreatePrivateKey(2048)
  //   fmt.Print(pk.PublicKey)
  // } else {
  //
  // }

  // Create a CSR struct
  csr := cert.CSR{
    CA: true,
    Passphrase: c.String("passphrase"),
    Size: c.Int("bits"),
    Days: c.Int("expire"),
    Key: pk,
    CN: cn,
    O: c.String("org"),
    OU: c.String("orgunit"),
    C: c.String("country"),
    S: c.String("state"),
    L: c.String("city"),
  }

  certificate, privatekey := cert.Make(csr)

  if !c.IsSet("output") {
    fmt.Print(string(certificate))
    fmt.Print(string(privatekey))
    // fmt.Print(string(pk))
  } else {
    println(c.String("output"))
  }
}
